In [2]:
import pandas as pd

In [ ]:
data={
    "name":["ritik","ritesh","tanisha","Mithu","Babu"],
    "age":[20,21,22,23,24],
    "salary":[50000,60000,70000,58000,78000],
    "perfromance salary":[85,90,78,58,75]
}
df=pd.DataFrame(data)
print(df)

In [5]:
df.to_csv("output.csv",index=True)
print(df)

      name  age  salary  perfromance salary
0    ritik   20   50000                  85
1   ritesh   21   60000                  90
2  tanisha   22   70000                  78
3    Mithu   23   58000                  58
4     Babu   24   78000                  75

In [6]:
df.describe()

             age        salary  perfromance salary
count   5.000000      5.000000            5.000000
mean   22.000000  63200.000000           77.200000
std     1.581139  10917.875251           12.235195
min    20.000000  50000.000000           58.000000
25%    21.000000  58000.000000           75.000000
50%    22.000000  60000.000000           78.000000
75%    23.000000  70000.000000           85.000000
max    24.000000  78000.000000           90.000000

In [7]:
df.shape

(5, 4)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                5 non-null      object
 1   age                 5 non-null      int64
 2   salary              5 non-null      int64
 3   perfromance salary  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [9]:
df.columns

Index(['name', 'age', 'salary', 'perfromance salary'], dtype='object')

In [10]:
df.head()

      name  age  salary  perfromance salary
0    ritik   20   50000                  85
1   ritesh   21   60000                  90
2  tanisha   22   70000                  78
3    Mithu   23   58000                  58
4     Babu   24   78000                  75

In [11]:
df.tail()

      name  age  salary  perfromance salary
0    ritik   20   50000                  85
1   ritesh   21   60000                  90
2  tanisha   22   70000                  78
3    Mithu   23   58000                  58
4     Babu   24   78000                  75

In [14]:
salary=df["salary"]
print(salary)

0    50000
1    60000
2    70000
3    58000
4    78000
Name: salary, dtype: int64

In [17]:
subset=df[["salary","name"]]
print(subset)

   salary     name
0   50000    ritik
1   60000   ritesh
2   70000  tanisha
3   58000    Mithu
4   78000     Babu

In [23]:
filtered_Rows=df[df["salary"]>45000]
print(filtered_Rows)

      name  age  salary  perfromance salary
0    ritik   20   50000                  85
1   ritesh   21   60000                  90
2  tanisha   22   70000                  78
3    Mithu   23   58000                  58
4     Babu   24   78000                  75

In [26]:
filtered_Rows=df[(df["salary"]>50000) & (df["age"]>20)]
print(filtered_Rows)

      name  age  salary  perfromance salary
1   ritesh   21   60000                  90
2  tanisha   22   70000                  78
3    Mithu   23   58000                  58
4     Babu   24   78000                  75